title: "Songjun Du 杜松骏"
description: "Personal website for research and projects"
url: "https://songjun113.github.io"
theme: minima

minima:
  skin: light
  social_links:
    github: https://github.com/Songjun113

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
